/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c CocosBuilderReader.jsb.ini" on 2013-11-11
* Script version: v0.6
*/
#import "jsb_config.h"
#if JSB_INCLUDE_COCOSBUILDERREADER

#import "jsb_NS_manual.h"
#import "CCBReader.h"
#import "CCBAnimationManager.h"

#import "jsfriendapi.h"
#import "jsb_config.h"
#import "jsb_core.h"
#import "jsb_basic_conversions.h"
#import "jsb_CocosBuilderReader_functions.h"


#endif // JSB_INCLUDE_COCOSBUILDERREADER
