/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c CCScrollView.jsb.ini" on 2013-11-10
* Script version: v0.6
*/
#import "jsb_config.h"
#if JSB_INCLUDE_CCSCROLLVIEW

#import "CCScrollView.h"
#import "js_bindings_cocos2d_ios_classes.h"


#endif // JSB_INCLUDE_CCSCROLLVIEW
