/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c CCControl.jsb.ini" on 2013-11-10
* Script version: v0.6
*/
#import "jsb_config.h"
#if JSB_INCLUDE_CCCONTROL

#import "CCControlExtension.h"
#import "js_bindings_cocos2d_ios_classes.h"
#import "js_bindings_NS_manual.h"
#import "js_bindings_cocos2d_manual.h"


#endif // JSB_INCLUDE_CCCONTROL
