/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c CCControl.jsb.ini" on 2013-11-10
* Script version: v0.6
*/
#import "jsb_config.h"
#if JSB_INCLUDE_CCCONTROL

#import "CCControlExtension.h"
#import "jsb_cocos2d_ios_classes.h"
#import "jsb_NS_manual.h"
#import "jsb_cocos2d_manual.h"

#import "jsfriendapi.h"
#import "jsb_config.h"
#import "jsb_core.h"
#import "jsb_basic_conversions.h"
#import "jsb_CCControl_functions.h"


#endif // JSB_INCLUDE_CCCONTROL
