/*
 * AUTOGENERATED FILE. DO NOT EDIT IT
 * Generated by "generate_jsb.py -c CCScrollView.jsb.ini" on 2013-11-10
 * Script version: v0.6
 */

var cc = cc || {};
cc.CCScrollViewDirectionBoth = 0x2;
cc.CCScrollViewDirectionHorizontal = 0x0;
cc.CCScrollViewDirectionVertical = 0x1;