/*
 * AUTOGENERATED FILE. DO NOT EDIT IT
 * Generated by "generate_jsb.py -c CCControl.jsb.ini" on 2013-11-10
 * Script version: v0.6
 */

var cc = cc || {};
cc.CCControlButtonMarginLR = 0x8;
cc.CCControlButtonMarginTB = 0x2;
cc.CCControlEventTouchCancel = 0x80;
cc.CCControlEventTouchDown = 0x1;
cc.CCControlEventTouchDragEnter = 0x8;
cc.CCControlEventTouchDragExit = 0x10;
cc.CCControlEventTouchDragInside = 0x2;
cc.CCControlEventTouchDragOutside = 0x4;
cc.CCControlEventTouchUpInside = 0x20;
cc.CCControlEventTouchUpOutside = 0x40;
cc.CCControlEventValueChanged = 0x100;
cc.CCControlStateDisabled = 0x4;
cc.CCControlStateHighlighted = 0x2;
cc.CCControlStateNormal = 0x1;
cc.CCControlStateSelected = 0x8;